config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :subscribers
  get '/premium', to: 'premium#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/premium_controller.rb
class PremiumController < BaseController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
end

app/controllers/subscribers_controller.rb
class SubscribersController < BaseController
  def new
  end

  def update
    token = params[:stripeToken]
    customer = Stripe::Customer.create(
      card: token,
      plan: 'plan_Gy1C2cKWJ4mizw',
      email: current_user.email
    )

    current_user.stripe_customer_id = customer.id
    current_user.stripe_response = customer.subscriptions["data"][0]
    current_user.save

    redirect_to premium_path
  end

  def show
    @subscription = current_user.stripe_response
  end

  def destroy
    @subscription_id = current_user.stripe_response['id']

    begin
      delete_subscription(@subscription_id)
      current_user.stripe_customer_id = nil
      current_user.stripe_response = nil
      current_user.save
    rescue Stripe::StripeError => e
      flash[:error] = e.message
    else
      flash[:notice] = "Your subscription has been cancelled successfully"
    end
    redirect_to root_path
  end

  def delete_subscription(subscription_id)
    Stripe::Subscription.delete(subscription_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < BaseController
  before_action :check_user_subsription!

  def index
  end

  private

  def check_user_subsription!
    redirect_to(premium_path) if current_user.stripe_customer_id?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/premium/index.html.erb
<div class="card" style="text-align: center;">
  <div class="card-header">
    <h5 class="card-title">Welcome</h5>
    <span style="float: right;">
      <% if user_signed_in? %>
        <%= current_user.email %>
        |
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </span>
  </div>
  <div class="card-body">
    <p class="card-text">Welcome To Ruby Subscription.</p>
    <p class="card-text">You are on <b>MANAGE SUBSCRIPTION </b>Page, please click on <b>Manage Subscription</b> to see your subscription details</p></p>
    <p style="padding: 103px;">
      <a href="#" class="btn btn-primary">Free Link 1</a>
      <a href="#" class="btn btn-primary">Free Link 2</a>
      <a href="#" class="btn btn-primary">Premium Link 1</a>
      <a href="#" class="btn btn-primary">Premium Link 1</a>
      <a href="<%= subscriber_path(current_user.id) %>" class="btn btn-primary">Manage Subscription</a>
    </p>
  </div>
</div>

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key]%>" data-description="Premium Plan Subscription" data-email="<%= current_user.email %>" data-amount="900">
  </script>
<% end %>

app/views/subscribers/new.html.erb
<div class="card" style="text-align: center;">
  <div class="card-header">
    <h5 class="card-title"><%= link_to('Welcome', root_path) %></h5>
    <span style="float: right;">
      <% if user_signed_in? %>
        <%= current_user.email %>
        |
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </span>
  </div>
  <div class="card-body">
    <p class="card-text">You are on <b>SUBSCRIBE</b> Page, please click on <b>Pay with Card</b> to subscribe</p>
    <p class="card-text">Subscribe using Stripe</p>
    <%= render 'form' %>
    <p class="card-text">$9 per month, cancel any time</p>
  </div>
</div>

app/views/subscribers/show.html.erb
<div class="card" style="text-align: center;">
  <div class="card-header">
    <h5 class="card-title"><%= link_to('Welcome', root_path) %> </h5>
    <span style="float: right;">
      <% if user_signed_in? %>
        <%= current_user.email %>
        |
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </span>
  </div>
</div>

<div class="card" style="text-align: center;">
  <div class="card-header">
    <p class="card-text">You are on <b>SUBSCRIPTION DETAILS </b>Page</p>
    <h6 class="card-title"><b><%= current_user.email %></b> on <b><%= @subscription['plan']['name'] %></b> . <b><%= @subscription['plan']['nickname'] %> </b>(<%= @subscription["status"] %>)</h6>
    <span>
      <%= link_to('Delete Subscription', subscriber_path(current_user.id), method: :delete, class: 'btn btn-primary') %>        
    </span>
  </div>
  <div class="card-body">
    <p class="card-text"><b>Next Invoice::</b> <%= (Time.at(@subscription["start_date"]).to_date  + 1.month).strftime("%b %d %Y") %></p>
    <p class="card-text"><b>Started::</b> <%= Time.at(@subscription["start_date"]).strftime("%b %d %Y") %></p>
  </div>
</div>

<div class="card" style="text-align: center;">
  <div class="card-header">
    <h6 class="card-title"><b>Pricing</b></h6>
  </div>
  <div class="card-body">
    <p class="card-text"><b>Plan::</b> <%= @subscription['plan']['name'] %> . <%= @subscription['plan']['nickname'] %></p>
    <p class="card-text"><b>Amount::</b> $<%= (@subscription['plan']['amount_decimal'].to_i/100)%> / <%= @subscription['plan']['interval']%></p>
    <p class="card-text"><b>Subscription ID::</b> <%= @subscription['id'] %></p>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="card" style="text-align: center;">
  <div class="card-header">
    <h5 class="card-title">Welcome</h5>
    <span style="float: right;">
      <% if user_signed_in? %>
        <%= current_user.email %>
        |
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </span>
  </div>
  <div class="card-body">
    <p class="card-text">Welcome To Ruby Subscription!!</p>
    <p class="card-text">You are on <b>GO PREMIUM </b>Page</p>
    <p style="padding: 103px;">
      <a href="#" class="btn btn-primary">Free Link 1</a>
      <a href="#" class="btn btn-primary">Free Link 2</a>
      <a href="<%= new_subscriber_path %>" class="btn btn-primary">Go Premium</a>
    </p>
  </div>
</div>